#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [ -n "$RTLSDRAIRBAND_CUSTOMCONFIG" ]; then
	/usr/local/bin/rtl_airband -c /run/rtlsdr-airband/rtl_airband.conf 
	#2>&1 \
	#	| stdbuf -o0 awk '{print "[rtlsdr-airband] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else 
	/usr/local/bin/rtl_airband -c /usr/local/etc/rtl_airband.conf 
	#2>&1 \
	#	| stdbuf -o0 awk '{print "[rtlsdr-airband] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi