#!/command/with-contenv bash
# shellcheck shell=bash

if [ -z "${ICECAST_DISABLE}" ]; then
	if [ -z "${ICECAST_CUSTOMCONFIG}" ]; then
		if [ -n "${ICECAST_ADMIN_PASSWORD}" ]; then
		    sed -i "s/<admin-password>[^<]*<\/admin-password>/<admin-password>$ICECAST_ADMIN_PASSWORD<\/admin-password>/g" /usr/local/etc/icecast.xml
		fi

		if [ -n "${ICECAST_ADMIN_USERNAME}" ]; then
		    sed -i "s/<admin-user>[^<]*<\/admin-user>/<admin-user>$ICECAST_ADMIN_USERNAME<\/admin-user>/g" /usr/local/etc/icecast.xml
		fi

		if [ -n "${ICECAST_ADMIN_EMAIL}" ]; then
		    sed -i "s/<admin>[^<]*<\/admin>/<admin>$ICECAST_ADMIN_EMAIL<\/admin>/g" /usr/local/etc/icecast.xml
		fi

		if [ -n "${ICECAST_LOCATION}" ]; then
		    sed -i "s/<location>[^<]*<\/location>/<location>$ICECAST_LOCATION<\/location>/g" /usr/local/etc/icecast.xml
		fi

		if [ -n "${ICECAST_HOSTNAME}" ]; then
		    sed -i "s/<hostname>[^<]*<\/hostname>/<hostname>$ICECAST_HOSTNAME<\/hostname>/g" /usr/local/etc/icecast.xml
		fi

		if [ -n "${ICECAST_MAX_CLIENTS}" ]; then
		    sed -i "s/<clients>[^<]*<\/clients>/<clients>$ICECAST_MAX_CLIENTS<\/clients>/g" /usr/local/etc/icecast.xml
		fi

		if [ -n "${ICECAST_MAX_SOURCES}" ]; then
		    sed -i "s/<sources>[^<]*<\/sources>/<sources>$ICECAST_MAX_SOURCES<\/sources>/g" /usr/local/etc/icecast.xml
		fi

		if [ -n "${PORT}" ]; then
		    sed -i "s/<port>8000<\/port>/<port>$PORT<\/port>/g" /usr/local/etc/icecast.xml
		fi
	else
		if [ -f "/run/rtlsdr-airband/icecast.xml" ]; then
			echo "Custom config provided. Ignoring Icecast environment variables"
		else
			echo "Icecast custom config option set but file not found. Aborting."
			exit 1
		fi
	fi
else
	echo "Icecast disabled. Please make sure a custom rtl_airband.conf file is provided."
fi

exit 0
