#!/command/with-contenv bash
#shellcheck shell=bash

if [ -z "${ICECAST_DISABLE}" ]; then
	# shellcheck disable=SC2016
	echo "Starting Icecast" 2>&1 \
		| stdbuf -o0 awk '{print "[icecast] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

	if [ -n "$ICECAST_CUSTOMCONFIG" ]; then
		# shellcheck disable=SC2016
		s6-setuidgid icecast2 icecast2 -c /run/rtlsdr-airband/icecast.xml 2>&1 \
		| stdbuf -o0 awk '{print "[icecast] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
	else
		# shellcheck disable=SC2016
		s6-setuidgid icecast2 icecast2 -c /usr/local/etc/icecast.xml 2>&1 \
		| stdbuf -o0 awk '{print "[icecast] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
	fi
else
	sleep 86400
fi

exit 0
