#!/usr/bin/with-contenv bash
#shellcheck shell=bash

tail -Fn0 /var/log/daemon.log | \
while read line ; do
        echo "$line" | awk '{split($0,a,": "); print "[rtlsdr-airband] " strftime("%Y/%m/%d %H:%M:%S", systime()) ": " a[2]}'
done