#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [ -z "${ICECAST_DISABLE}" ]; then
	echo "Starting Icecast"
	s6-setuidgid icecast2 icecast2 -c /usr/local/etc/icecast.xml
else
	echo "Icecast disabled"
fi
