#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [ -z "${ICECAST_DISABLE}" ]; then
	echo "Starting Icecast"

	if [ -n "$ICECAST_CUSTOMCONFIG" ]; then
		s6-setuidgid icecast2 icecast2 -c /run/rtlsdr-airband/icecast.xml
	else 
		s6-setuidgid icecast2 icecast2 -c /usr/local/etc/icecast.xml
	fi
else
	echo "Icecast disabled"
fi

exit 0